<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Zavu\Sdk\Models\Operations;

use Zavu\Sdk\Utils\SpeakeasyMetadata;
class DeleteTemplateRequest
{
    /**
     *
     * @var string $templateId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=templateId')]
    public string $templateId;

    /**
     * @param  string  $templateId
     * @phpstan-pure
     */
    public function __construct(string $templateId)
    {
        $this->templateId = $templateId;
    }
}