<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Zavu\Sdk\Models\Operations;

use Zavu\Sdk\Utils\SpeakeasyMetadata;
class GetContactByPhoneRequest
{
    /**
     * E.164 phone number.
     *
     * @var string $phoneNumber
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=phoneNumber')]
    public string $phoneNumber;

    /**
     * @param  string  $phoneNumber
     * @phpstan-pure
     */
    public function __construct(string $phoneNumber)
    {
        $this->phoneNumber = $phoneNumber;
    }
}