<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Zavu\Sdk\Models\Operations;

use Zavu\Sdk\Utils\SpeakeasyMetadata;
class GetContactRequest
{
    /**
     *
     * @var string $contactId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=contactId')]
    public string $contactId;

    /**
     * @param  string  $contactId
     * @phpstan-pure
     */
    public function __construct(string $contactId)
    {
        $this->contactId = $contactId;
    }
}