<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Zavu\Sdk\Models\Operations;

use Zavu\Sdk\Utils\SpeakeasyMetadata;
class GetMessageRequest
{
    /**
     *
     * @var string $messageId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=messageId')]
    public string $messageId;

    /**
     * @param  string  $messageId
     * @phpstan-pure
     */
    public function __construct(string $messageId)
    {
        $this->messageId = $messageId;
    }
}