<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Zavu\Sdk\Models\Operations;

use Zavu\Sdk\Utils\SpeakeasyMetadata;
class GetSenderRequest
{
    /**
     *
     * @var string $senderId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=senderId')]
    public string $senderId;

    /**
     * @param  string  $senderId
     * @phpstan-pure
     */
    public function __construct(string $senderId)
    {
        $this->senderId = $senderId;
    }
}