<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Zavu\Sdk\Models\Operations;

use Zavu\Sdk\Utils\SpeakeasyMetadata;
class ListContactsRequest
{
    /**
     *
     * @var ?string $phoneNumber
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=phoneNumber')]
    public ?string $phoneNumber = null;

    /**
     *
     * @var ?string $cursor
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=cursor')]
    public ?string $cursor = null;

    /**
     *
     * @var ?int $limit
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=limit')]
    public ?int $limit = null;

    /**
     * @param  ?string  $phoneNumber
     * @param  ?int  $limit
     * @param  ?string  $cursor
     * @phpstan-pure
     */
    public function __construct(?string $phoneNumber = null, ?string $cursor = null, ?int $limit = 50)
    {
        $this->phoneNumber = $phoneNumber;
        $this->cursor = $cursor;
        $this->limit = $limit;
    }
}