<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Zavu\Sdk\Models\Operations;

use Zavu\Sdk\Models\Components;
/** ListMessagesResponseBody - List of messages. */
class ListMessagesResponseBody
{
    /**
     * $items
     *
     * @var array<Components\Message> $items
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('items')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Zavu\Sdk\Models\Components\Message>')]
    public array $items;

    /**
     *
     * @var ?string $nextCursor
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('nextCursor')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $nextCursor = null;

    /**
     * @param  array<Components\Message>  $items
     * @param  ?string  $nextCursor
     * @phpstan-pure
     */
    public function __construct(array $items, ?string $nextCursor = null)
    {
        $this->items = $items;
        $this->nextCursor = $nextCursor;
    }
}