<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Zavu\Sdk\Models\Operations;

use Zavu\Sdk\Models\Components;
/** ListTemplatesResponseBody - List of templates. */
class ListTemplatesResponseBody
{
    /**
     * $items
     *
     * @var array<Components\Template> $items
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('items')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Zavu\Sdk\Models\Components\Template>')]
    public array $items;

    /**
     * @param  array<Components\Template>  $items
     * @phpstan-pure
     */
    public function __construct(array $items)
    {
        $this->items = $items;
    }
}