<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Zavu\Sdk\Models\Operations;

use Zavu\Sdk\Models\Components;
use Zavu\Sdk\Utils\SpeakeasyMetadata;
class ListMessagesRequest
{
    /**
     *
     * @var ?Components\MessageStatus $status
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=status')]
    public ?Components\MessageStatus $status = null;

    /**
     *
     * @var ?string $to
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=to')]
    public ?string $to = null;

    /**
     * Delivery channel.
     *
     * @var ?Components\Channel $channel
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=channel')]
    public ?Components\Channel $channel = null;

    /**
     *
     * @var ?string $cursor
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=cursor')]
    public ?string $cursor = null;

    /**
     *
     * @var ?int $limit
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=limit')]
    public ?int $limit = null;

    /**
     * @param  ?Components\MessageStatus  $status
     * @param  ?string  $to
     * @param  ?Components\Channel  $channel
     * @param  ?int  $limit
     * @param  ?string  $cursor
     * @phpstan-pure
     */
    public function __construct(?Components\MessageStatus $status = null, ?string $to = null, ?Components\Channel $channel = null, ?string $cursor = null, ?int $limit = 50)
    {
        $this->status = $status;
        $this->to = $to;
        $this->channel = $channel;
        $this->cursor = $cursor;
        $this->limit = $limit;
    }
}