<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Zavu\Sdk\Models\Operations;

use Zavu\Sdk\Models\Components;
use Zavu\Sdk\Utils\SpeakeasyMetadata;
class SendMessageRequest
{
    /**
     *
     * @var Components\MessageRequest $body
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\MessageRequest $body;

    /**
     * Optional sender profile ID. If omitted, the project's default sender will be used.
     *
     * @var ?string $zavuSender
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=Zavu-Sender')]
    public ?string $zavuSender = null;

    /**
     * @param  Components\MessageRequest  $body
     * @param  ?string  $zavuSender
     * @phpstan-pure
     */
    public function __construct(Components\MessageRequest $body, ?string $zavuSender = null)
    {
        $this->body = $body;
        $this->zavuSender = $zavuSender;
    }
}