<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Zavu\Sdk\Models\Operations;

use Zavu\Sdk\Models\Components;
use Zavu\Sdk\Utils\SpeakeasyMetadata;
class SendReactionRequest
{
    /**
     *
     * @var string $messageId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=messageId')]
    public string $messageId;

    /**
     *
     * @var Components\ReactionRequest $body
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\ReactionRequest $body;

    /**
     * Optional sender profile ID. If omitted, the project's default sender will be used.
     *
     * @var ?string $zavuSender
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=Zavu-Sender')]
    public ?string $zavuSender = null;

    /**
     * @param  string  $messageId
     * @param  Components\ReactionRequest  $body
     * @param  ?string  $zavuSender
     * @phpstan-pure
     */
    public function __construct(string $messageId, Components\ReactionRequest $body, ?string $zavuSender = null)
    {
        $this->messageId = $messageId;
        $this->body = $body;
        $this->zavuSender = $zavuSender;
    }
}