<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Zavu\Sdk\Models\Operations;

use Zavu\Sdk\Models\Components;
use Zavu\Sdk\Utils\SpeakeasyMetadata;
class UpdateSenderRequest
{
    /**
     *
     * @var string $senderId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=senderId')]
    public string $senderId;

    /**
     *
     * @var Components\SenderUpdateRequest $body
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\SenderUpdateRequest $body;

    /**
     * @param  string  $senderId
     * @param  Components\SenderUpdateRequest  $body
     * @phpstan-pure
     */
    public function __construct(string $senderId, Components\SenderUpdateRequest $body)
    {
        $this->senderId = $senderId;
        $this->body = $body;
    }
}