<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Zavu\Sdk\Models\Operations;

use Zavu\Sdk\Models\Components;
use Zavu\Sdk\Utils\SpeakeasyMetadata;
class UpdateContactRequest
{
    /**
     *
     * @var string $contactId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=contactId')]
    public string $contactId;

    /**
     *
     * @var Components\ContactUpdateRequest $body
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\ContactUpdateRequest $body;

    /**
     * @param  string  $contactId
     * @param  Components\ContactUpdateRequest  $body
     * @phpstan-pure
     */
    public function __construct(string $contactId, Components\ContactUpdateRequest $body)
    {
        $this->contactId = $contactId;
        $this->body = $body;
    }
}