<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Zavu\Sdk\Models\Components;


class Capabilities
{
    /**
     * Whether SMS is enabled for this sender.
     *
     * @var ?bool $sms
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('sms')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $sms = null;

    /**
     * Whether WhatsApp is enabled for this sender.
     *
     * @var ?bool $whatsapp
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('whatsapp')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $whatsapp = null;

    /**
     * @param  ?bool  $sms
     * @param  ?bool  $whatsapp
     * @phpstan-pure
     */
    public function __construct(?bool $sms = null, ?bool $whatsapp = null)
    {
        $this->sms = $sms;
        $this->whatsapp = $whatsapp;
    }
}