<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Zavu\Sdk\Models\Components;


/** Delivery channel. */
enum Channel: string
{
    case Sms = 'sms';
    case Whatsapp = 'whatsapp';
}
