<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Zavu\Sdk\Models\Components;


class Contact
{
    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     * E.164 phone number.
     *
     * @var string $phoneNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('phoneNumber')]
    public string $phoneNumber;

    /**
     *
     * @var ?string $countryCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('countryCode')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $countryCode = null;

    /**
     * Whether the 24-hour WhatsApp window is currently open.
     *
     * @var ?bool $whatsappWindowOpen
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('whatsappWindowOpen')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $whatsappWindowOpen = null;

    /**
     * When the contact last messaged via WhatsApp.
     *
     * @var ?\DateTime $lastWhatsappMessageAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('lastWhatsappMessageAt')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $lastWhatsappMessageAt = null;

    /**
     * $metadata
     *
     * @var ?array<string, string> $metadata
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('metadata')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $metadata = null;

    /**
     *
     * @var ?\DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('createdAt')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $createdAt = null;

    /**
     *
     * @var ?\DateTime $updatedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('updatedAt')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $updatedAt = null;

    /**
     * @param  string  $id
     * @param  string  $phoneNumber
     * @param  ?string  $countryCode
     * @param  ?bool  $whatsappWindowOpen
     * @param  ?\DateTime  $lastWhatsappMessageAt
     * @param  ?array<string, string>  $metadata
     * @param  ?\DateTime  $createdAt
     * @param  ?\DateTime  $updatedAt
     * @phpstan-pure
     */
    public function __construct(string $id, string $phoneNumber, ?string $countryCode = null, ?bool $whatsappWindowOpen = null, ?\DateTime $lastWhatsappMessageAt = null, ?array $metadata = null, ?\DateTime $createdAt = null, ?\DateTime $updatedAt = null)
    {
        $this->id = $id;
        $this->phoneNumber = $phoneNumber;
        $this->countryCode = $countryCode;
        $this->whatsappWindowOpen = $whatsappWindowOpen;
        $this->lastWhatsappMessageAt = $lastWhatsappMessageAt;
        $this->metadata = $metadata;
        $this->createdAt = $createdAt;
        $this->updatedAt = $updatedAt;
    }
}