<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Zavu\Sdk\Models\Components;


/** MessageRequest - Request body to send a message. */
class MessageRequest
{
    /**
     * Recipient phone number in E.164 format.
     *
     * @var string $to
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('to')]
    public string $to;

    /**
     * Delivery channel.
     *
     * @var ?Channel $channel
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('channel')]
    #[\Speakeasy\Serializer\Annotation\Type('\Zavu\Sdk\Models\Components\Channel|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Channel $channel = null;

    /**
     * Type of message. Non-text types are WhatsApp only.
     *
     * @var ?MessageType $messageType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('messageType')]
    #[\Speakeasy\Serializer\Annotation\Type('\Zavu\Sdk\Models\Components\MessageType|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?MessageType $messageType = null;

    /**
     * Text body for text messages or caption for media messages.
     *
     * @var ?string $text
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('text')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $text = null;

    /**
     * Content for non-text message types (WhatsApp only).
     *
     * @var ?MessageContent $content
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('content')]
    #[\Speakeasy\Serializer\Annotation\Type('\Zavu\Sdk\Models\Components\MessageContent|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?MessageContent $content = null;

    /**
     * Optional idempotency key to avoid duplicate sends.
     *
     * @var ?string $idempotencyKey
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('idempotencyKey')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $idempotencyKey = null;

    /**
     * Arbitrary metadata to associate with the message.
     *
     * @var ?array<string, string> $metadata
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('metadata')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $metadata = null;

    /**
     * @param  string  $to
     * @param  ?Channel  $channel
     * @param  ?MessageType  $messageType
     * @param  ?string  $text
     * @param  ?MessageContent  $content
     * @param  ?string  $idempotencyKey
     * @param  ?array<string, string>  $metadata
     * @phpstan-pure
     */
    public function __construct(string $to, ?Channel $channel = null, ?MessageType $messageType = null, ?string $text = null, ?MessageContent $content = null, ?string $idempotencyKey = null, ?array $metadata = null)
    {
        $this->to = $to;
        $this->channel = $channel;
        $this->messageType = $messageType;
        $this->text = $text;
        $this->content = $content;
        $this->idempotencyKey = $idempotencyKey;
        $this->metadata = $metadata;
    }
}