<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Zavu\Sdk\Models\Components;


class Message
{
    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var string $to
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('to')]
    public string $to;

    /**
     * Delivery channel.
     *
     * @var Channel $channel
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('channel')]
    #[\Speakeasy\Serializer\Annotation\Type('\Zavu\Sdk\Models\Components\Channel')]
    public Channel $channel;

    /**
     * Type of message. Non-text types are WhatsApp only.
     *
     * @var MessageType $messageType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('messageType')]
    #[\Speakeasy\Serializer\Annotation\Type('\Zavu\Sdk\Models\Components\MessageType')]
    public MessageType $messageType;

    /**
     *
     * @var MessageStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Zavu\Sdk\Models\Components\MessageStatus')]
    public MessageStatus $status;

    /**
     *
     * @var \DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('createdAt')]
    public \DateTime $createdAt;

    /**
     *
     * @var ?string $from
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('from')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $from = null;

    /**
     *
     * @var ?string $senderId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('senderId')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $senderId = null;

    /**
     * Text content or caption.
     *
     * @var ?string $text
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('text')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $text = null;

    /**
     * Content for non-text message types (WhatsApp only).
     *
     * @var ?MessageContent $content
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('content')]
    #[\Speakeasy\Serializer\Annotation\Type('\Zavu\Sdk\Models\Components\MessageContent|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?MessageContent $content = null;

    /**
     * Message ID from the delivery provider.
     *
     * @var ?string $providerMessageId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('providerMessageId')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $providerMessageId = null;

    /**
     * $metadata
     *
     * @var ?array<string, string> $metadata
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('metadata')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $metadata = null;

    /**
     *
     * @var ?\DateTime $updatedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('updatedAt')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $updatedAt = null;

    /**
     *
     * @var ?string $errorCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('errorCode')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $errorCode = null;

    /**
     *
     * @var ?string $errorMessage
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('errorMessage')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $errorMessage = null;

    /**
     * @param  string  $id
     * @param  string  $to
     * @param  Channel  $channel
     * @param  MessageType  $messageType
     * @param  MessageStatus  $status
     * @param  \DateTime  $createdAt
     * @param  ?string  $from
     * @param  ?string  $senderId
     * @param  ?string  $text
     * @param  ?MessageContent  $content
     * @param  ?string  $providerMessageId
     * @param  ?array<string, string>  $metadata
     * @param  ?\DateTime  $updatedAt
     * @param  ?string  $errorCode
     * @param  ?string  $errorMessage
     * @phpstan-pure
     */
    public function __construct(string $id, string $to, Channel $channel, MessageType $messageType, MessageStatus $status, \DateTime $createdAt, ?string $from = null, ?string $senderId = null, ?string $text = null, ?MessageContent $content = null, ?string $providerMessageId = null, ?array $metadata = null, ?\DateTime $updatedAt = null, ?string $errorCode = null, ?string $errorMessage = null)
    {
        $this->id = $id;
        $this->to = $to;
        $this->channel = $channel;
        $this->messageType = $messageType;
        $this->status = $status;
        $this->createdAt = $createdAt;
        $this->from = $from;
        $this->senderId = $senderId;
        $this->text = $text;
        $this->content = $content;
        $this->providerMessageId = $providerMessageId;
        $this->metadata = $metadata;
        $this->updatedAt = $updatedAt;
        $this->errorCode = $errorCode;
        $this->errorMessage = $errorMessage;
    }
}