<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Zavu\Sdk\Models\Components;


class MessageResponse
{
    /**
     *
     * @var Message $message
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('message')]
    #[\Speakeasy\Serializer\Annotation\Type('\Zavu\Sdk\Models\Components\Message')]
    public Message $message;

    /**
     * @param  Message  $message
     * @phpstan-pure
     */
    public function __construct(Message $message)
    {
        $this->message = $message;
    }
}