<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Zavu\Sdk\Models\Components;


/** MessageContent - Content for non-text message types (WhatsApp only). */
class MessageContent
{
    /**
     * URL of the media file (for image, video, audio, document, sticker).
     *
     * @var ?string $mediaUrl
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('mediaUrl')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $mediaUrl = null;

    /**
     * WhatsApp media ID if already uploaded.
     *
     * @var ?string $mediaId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('mediaId')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $mediaId = null;

    /**
     * MIME type of the media.
     *
     * @var ?string $mimeType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('mimeType')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $mimeType = null;

    /**
     * Filename for documents.
     *
     * @var ?string $filename
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('filename')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $filename = null;

    /**
     * Latitude for location messages.
     *
     * @var ?float $latitude
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('latitude')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $latitude = null;

    /**
     * Longitude for location messages.
     *
     * @var ?float $longitude
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('longitude')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $longitude = null;

    /**
     * Name of the location.
     *
     * @var ?string $locationName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('locationName')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $locationName = null;

    /**
     * Address of the location.
     *
     * @var ?string $locationAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('locationAddress')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $locationAddress = null;

    /**
     * Contact cards for contact messages.
     *
     * @var ?array<MessageContentContact> $contacts
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('contacts')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Zavu\Sdk\Models\Components\MessageContentContact>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $contacts = null;

    /**
     * Interactive buttons (max 3).
     *
     * @var ?array<Button> $buttons
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('buttons')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Zavu\Sdk\Models\Components\Button>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $buttons = null;

    /**
     * Button text for list messages.
     *
     * @var ?string $listButton
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('listButton')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $listButton = null;

    /**
     * Sections for list messages.
     *
     * @var ?array<Section> $sections
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('sections')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Zavu\Sdk\Models\Components\Section>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $sections = null;

    /**
     * Emoji for reaction messages.
     *
     * @var ?string $emoji
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('emoji')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $emoji = null;

    /**
     * Message ID to react to.
     *
     * @var ?string $reactToMessageId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('reactToMessageId')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $reactToMessageId = null;

    /**
     * Template ID for template messages.
     *
     * @var ?string $templateId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('templateId')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $templateId = null;

    /**
     * Variables for template rendering. Keys are variable positions (1, 2, 3...).
     *
     * @var ?array<string, string> $templateVariables
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('templateVariables')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $templateVariables = null;

    /**
     * @param  ?string  $mediaUrl
     * @param  ?string  $mediaId
     * @param  ?string  $mimeType
     * @param  ?string  $filename
     * @param  ?float  $latitude
     * @param  ?float  $longitude
     * @param  ?string  $locationName
     * @param  ?string  $locationAddress
     * @param  ?array<MessageContentContact>  $contacts
     * @param  ?array<Button>  $buttons
     * @param  ?string  $listButton
     * @param  ?array<Section>  $sections
     * @param  ?string  $emoji
     * @param  ?string  $reactToMessageId
     * @param  ?string  $templateId
     * @param  ?array<string, string>  $templateVariables
     * @phpstan-pure
     */
    public function __construct(?string $mediaUrl = null, ?string $mediaId = null, ?string $mimeType = null, ?string $filename = null, ?float $latitude = null, ?float $longitude = null, ?string $locationName = null, ?string $locationAddress = null, ?array $contacts = null, ?array $buttons = null, ?string $listButton = null, ?array $sections = null, ?string $emoji = null, ?string $reactToMessageId = null, ?string $templateId = null, ?array $templateVariables = null)
    {
        $this->mediaUrl = $mediaUrl;
        $this->mediaId = $mediaId;
        $this->mimeType = $mimeType;
        $this->filename = $filename;
        $this->latitude = $latitude;
        $this->longitude = $longitude;
        $this->locationName = $locationName;
        $this->locationAddress = $locationAddress;
        $this->contacts = $contacts;
        $this->buttons = $buttons;
        $this->listButton = $listButton;
        $this->sections = $sections;
        $this->emoji = $emoji;
        $this->reactToMessageId = $reactToMessageId;
        $this->templateId = $templateId;
        $this->templateVariables = $templateVariables;
    }
}