<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Zavu\Sdk\Models\Components;


/** Type of message. Non-text types are WhatsApp only. */
enum MessageType: string
{
    case Text = 'text';
    case Image = 'image';
    case Video = 'video';
    case Audio = 'audio';
    case Document = 'document';
    case Sticker = 'sticker';
    case Location = 'location';
    case Contact = 'contact';
    case Buttons = 'buttons';
    case List = 'list';
    case Reaction = 'reaction';
    case Template = 'template';
}
