<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Zavu\Sdk\Models\Components;


class MessageContentContact
{
    /**
     *
     * @var ?string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $name = null;

    /**
     * $phones
     *
     * @var ?array<string> $phones
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('phones')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $phones = null;

    /**
     * @param  ?string  $name
     * @param  ?array<string>  $phones
     * @phpstan-pure
     */
    public function __construct(?string $name = null, ?array $phones = null)
    {
        $this->name = $name;
        $this->phones = $phones;
    }
}