<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Zavu\Sdk\Models\Components;


class PhoneIntrospectionResponse
{
    /**
     *
     * @var string $phoneNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('phoneNumber')]
    public string $phoneNumber;

    /**
     *
     * @var string $countryCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('countryCode')]
    public string $countryCode;

    /**
     *
     * @var bool $validNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('validNumber')]
    public bool $validNumber;

    /**
     * Whether a 24h WhatsApp window is open for this number.
     *
     * @var ?bool $whatsappWindowOpen
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('whatsappWindowOpen')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $whatsappWindowOpen = null;

    /**
     * @param  string  $phoneNumber
     * @param  string  $countryCode
     * @param  bool  $validNumber
     * @param  ?bool  $whatsappWindowOpen
     * @phpstan-pure
     */
    public function __construct(string $phoneNumber, string $countryCode, bool $validNumber, ?bool $whatsappWindowOpen = null)
    {
        $this->phoneNumber = $phoneNumber;
        $this->countryCode = $countryCode;
        $this->validNumber = $validNumber;
        $this->whatsappWindowOpen = $whatsappWindowOpen;
    }
}