<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Zavu\Sdk\Models\Components;


class ReactionRequest
{
    /**
     * Single emoji character to react with.
     *
     * @var string $emoji
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('emoji')]
    public string $emoji;

    /**
     * @param  string  $emoji
     * @phpstan-pure
     */
    public function __construct(string $emoji)
    {
        $this->emoji = $emoji;
    }
}