<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Zavu\Sdk\Models\Components;


class Section
{
    /**
     *
     * @var string $title
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('title')]
    public string $title;

    /**
     * $rows
     *
     * @var array<Row> $rows
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('rows')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Zavu\Sdk\Models\Components\Row>')]
    public array $rows;

    /**
     * @param  string  $title
     * @param  array<Row>  $rows
     * @phpstan-pure
     */
    public function __construct(string $title, array $rows)
    {
        $this->title = $title;
        $this->rows = $rows;
    }
}