<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Zavu\Sdk\Models\Components;


class SenderUpdateRequest
{
    /**
     *
     * @var ?string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $name = null;

    /**
     *
     * @var ?bool $setAsDefault
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('setAsDefault')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $setAsDefault = null;

    /**
     * @param  ?string  $name
     * @param  ?bool  $setAsDefault
     * @phpstan-pure
     */
    public function __construct(?string $name = null, ?bool $setAsDefault = null)
    {
        $this->name = $name;
        $this->setAsDefault = $setAsDefault;
    }
}