<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Zavu\Sdk\Models\Components;


class Sender
{
    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     * Phone number in E.164 format.
     *
     * @var string $phoneNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('phoneNumber')]
    public string $phoneNumber;

    /**
     *
     * @var ?Capabilities $capabilities
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('capabilities')]
    #[\Speakeasy\Serializer\Annotation\Type('\Zavu\Sdk\Models\Components\Capabilities|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Capabilities $capabilities = null;

    /**
     *
     * @var ?\DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('createdAt')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $createdAt = null;

    /**
     *
     * @var ?\DateTime $updatedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('updatedAt')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $updatedAt = null;

    /**
     * Whether this sender is the project's default.
     *
     * @var ?bool $isDefault
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('isDefault')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $isDefault = null;

    /**
     * @param  string  $id
     * @param  string  $name
     * @param  string  $phoneNumber
     * @param  ?bool  $isDefault
     * @param  ?Capabilities  $capabilities
     * @param  ?\DateTime  $createdAt
     * @param  ?\DateTime  $updatedAt
     * @phpstan-pure
     */
    public function __construct(string $id, string $name, string $phoneNumber, ?Capabilities $capabilities = null, ?\DateTime $createdAt = null, ?\DateTime $updatedAt = null, ?bool $isDefault = false)
    {
        $this->id = $id;
        $this->name = $name;
        $this->phoneNumber = $phoneNumber;
        $this->capabilities = $capabilities;
        $this->createdAt = $createdAt;
        $this->updatedAt = $updatedAt;
        $this->isDefault = $isDefault;
    }
}