<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Zavu\Sdk\Models\Components;


class SenderCreateRequest
{
    /**
     *
     * @var string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     *
     * @var string $phoneNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('phoneNumber')]
    public string $phoneNumber;

    /**
     *
     * @var ?bool $setAsDefault
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('setAsDefault')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $setAsDefault = null;

    /**
     * @param  string  $name
     * @param  string  $phoneNumber
     * @param  ?bool  $setAsDefault
     * @phpstan-pure
     */
    public function __construct(string $name, string $phoneNumber, ?bool $setAsDefault = false)
    {
        $this->name = $name;
        $this->phoneNumber = $phoneNumber;
        $this->setAsDefault = $setAsDefault;
    }
}