<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Zavu\Sdk\Models\Components;


class TemplateCreateRequest
{
    /**
     *
     * @var string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     *
     * @var string $body
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('body')]
    public string $body;

    /**
     * WhatsApp template category.
     *
     * @var ?WhatsAppCategory $whatsappCategory
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('whatsappCategory')]
    #[\Speakeasy\Serializer\Annotation\Type('\Zavu\Sdk\Models\Components\WhatsAppCategory|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?WhatsAppCategory $whatsappCategory = null;

    /**
     * $variables
     *
     * @var ?array<string> $variables
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('variables')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $variables = null;

    /**
     *
     * @var ?string $language
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('language')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $language = null;

    /**
     * @param  string  $name
     * @param  string  $body
     * @param  ?string  $language
     * @param  ?WhatsAppCategory  $whatsappCategory
     * @param  ?array<string>  $variables
     * @phpstan-pure
     */
    public function __construct(string $name, string $body, ?WhatsAppCategory $whatsappCategory = null, ?array $variables = null, ?string $language = 'en')
    {
        $this->name = $name;
        $this->body = $body;
        $this->whatsappCategory = $whatsappCategory;
        $this->variables = $variables;
        $this->language = $language;
    }
}