<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Zavu\Sdk\Models\Components;


class Template
{
    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     * Template name (must match WhatsApp template name).
     *
     * @var string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     * Language code.
     *
     * @var string $language
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('language')]
    public string $language;

    /**
     * Template body with variables: {{"{{"}}1}}, {{"{{"}}2}}, etc.
     *
     * @var string $body
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('body')]
    public string $body;

    /**
     * WhatsApp template category.
     *
     * @var WhatsAppCategory $category
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('category')]
    #[\Speakeasy\Serializer\Annotation\Type('\Zavu\Sdk\Models\Components\WhatsAppCategory')]
    public WhatsAppCategory $category;

    /**
     * List of variable names for documentation.
     *
     * @var ?array<string> $variables
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('variables')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $variables = null;

    /**
     *
     * @var ?\DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('createdAt')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $createdAt = null;

    /**
     *
     * @var ?\DateTime $updatedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('updatedAt')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $updatedAt = null;

    /**
     *
     * @var ?Status $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Zavu\Sdk\Models\Components\Status|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Status $status = null;

    /**
     * @param  string  $id
     * @param  string  $name
     * @param  string  $language
     * @param  string  $body
     * @param  WhatsAppCategory  $category
     * @param  ?Status  $status
     * @param  ?array<string>  $variables
     * @param  ?\DateTime  $createdAt
     * @param  ?\DateTime  $updatedAt
     * @phpstan-pure
     */
    public function __construct(string $id, string $name, string $language, string $body, WhatsAppCategory $category, ?array $variables = null, ?\DateTime $createdAt = null, ?\DateTime $updatedAt = null, ?Status $status = Status::Pending)
    {
        $this->id = $id;
        $this->name = $name;
        $this->language = $language;
        $this->body = $body;
        $this->category = $category;
        $this->variables = $variables;
        $this->createdAt = $createdAt;
        $this->updatedAt = $updatedAt;
        $this->status = $status;
    }
}