<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Zavu\Sdk\Models\Components;


/** WhatsApp template category. */
enum WhatsAppCategory: string
{
    case Utility = 'UTILITY';
    case Marketing = 'MARKETING';
    case Authentication = 'AUTHENTICATION';
}
