<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Zavu\Sdk;

use Zavu\Sdk\Utils\Retry;

/**
 * ZavuBuilder is used to configure and build an instance of the SDK.
 */
class ZavuBuilder
{
    public function __construct(
        private SDKConfiguration $sdkConfig = new SDKConfiguration(),
    ) {
    }

    /**
     * setClient allows setting a custom Guzzle client for the SDK to make requests with.
     *
     * @param  \GuzzleHttp\ClientInterface  $client
     * @return ZavuBuilder
     */
    public function setClient(\GuzzleHttp\ClientInterface $client): ZavuBuilder
    {
        $this->sdkConfig->client = $client;

        return $this;
    }

    /**
     * setSecurity is used to configure the security required for the SDK.
     *
     * @param  string  $bearerAuth
     * @return ZavuBuilder
     */
    public function setSecurity(string $bearerAuth): ZavuBuilder
    {
        $security = new Models\Components\Security(
            bearerAuth: $bearerAuth
        );
        $this->sdkConfig->securitySource = fn () => $security;

        return $this;
    }

    /**
     * setSecuritySource is usd to configure the security required for the SDK.
     * unlike setSecurity, setSecuritySource accepts a closure that will be called to retrieve the security information.
     *
     * @param  pure-Closure(): string  $securitySource
     * @return ZavuBuilder
     */
    public function setSecuritySource(\Closure $securitySource): ZavuBuilder
    {
        $this->sdkConfig->securitySource = fn () => new Models\Components\Security(bearerAuth: $securitySource());

        return $this;
    }

    /**
     * setServerUrl is used to configure the server URL for the SDK, and optionally template any parameters in the URL.
     *
     * @param  string  $serverUrl
     * @param  array<string, string>  $params
     * @return ZavuBuilder
     */
    public function setServerUrl(string $serverUrl, ?array $params = null): ZavuBuilder
    {
        $this->sdkConfig->serverUrl = Utils\Utils::templateUrl($serverUrl, $params);

        return $this;
    }

    /**
     * setServer is used to configure the server for the SDK
     *
     * @param  int  $serverIdx
     * @return ZavuBuilder
     */
    public function setServerIndex(int $serverIdx): ZavuBuilder
    {
        $this->sdkConfig->serverIndex = $serverIdx;

        return $this;
    }

    public function setRetryConfig(Retry\RetryConfig $config): ZavuBuilder
    {
        $this->sdkConfig->retryConfig = $config;

        return $this;
    }

    /**
     * build is used to build the SDK with any of the configured options.
     *
     * @return Zavu
     */
    public function build(): Zavu
    {
        if ($this->sdkConfig->client === null) {
            $this->sdkConfig->client = new \GuzzleHttp\Client([
                'timeout' => 60,
            ]);
        }
        if ($this->sdkConfig->hasSecurity()) {
            $this->sdkConfig->client = Utils\Utils::configureSecurityClient($this->sdkConfig->client, $this->sdkConfig->getSecurity());
        }

        return new Zavu($this->sdkConfig);
    }
}